network:
  ethernets:
    eno1:
      dhcp4: false
    eno2:
      dhcp4: false
    eno3:
      dhcp4: false
    eno4:
      dhcp4: false
  bonds:
    bond0:
      gateway4: 192.168.1.1
      addresses:
      - 192.168.1.2/24
      interfaces:
      - eno1
      - eno2
      parameters:
        mode: active-backup
        primary: eno1
      nameservers:
        addresses:
        - 192.168.1.2
        - 192.168.1.1
    bond1:
      optional: true
      gateway4: 192.168.1.1
      addresses:
      - 192.168.2.1/24
      - 192.168.1.3/24
      interfaces:
      - eno3
      - eno4
      parameters:
        mode: active-backup
        primary: eno3
      routes:
      - to: 192.168.1.0/24
        via: 192.168.1.3
      nameservers:
        addresses:
        - 192.168.1.2
        - 192.168.2.1
  vlans:
    vlan.01:
      id: 01
      link: bond0
      addresses:
      - 10.0.0.1/24
      nameservers:
        addresses:
        - 10.0.0.1
    vlan.02:
      id: 02
      link: bond0
      addresses:
      - 10.0.1.1/24
      nameservers:
        addresses:
        - 10.0.1.1
    vlan.03:
      id: 03
      link: bond0
      addresses:
      - 10.0.2.1/24
      nameservers:
        addresses:
        - 10.0.2.1
    vlan.11:
      id: 11
      link: bond0
      addresses:
      - 10.1.0.1/24
      nameservers:
        addresses:
        - 10.1.0.1
    vlan.12:
      id: 12
      link: bond0
      addresses:
      - 10.1.1.1/24
      nameservers:
        addresses:
        - 10.1.1.1
    vlan.13:
      id: 13
      link: bond0
      addresses:
      - 10.1.2.1/24
      nameservers:
        addresses:
        - 10.1.2.1
    vlan.21:
      id: 21
      link: bond1
      addresses:
      - 10.2.0.1/24
      nameservers:
        addresses:
        - 10.2.0.1
    vlan.22:
      id: 22
      link: bond1
      addresses:
      - 10.2.1.1/24
      nameservers:
        addresses:
        - 10.2.1.1
    vlan.23:
      id: 23
      link: bond1
      addresses:
      - 10.2.2.1/24
      nameservers:
        addresses:
        - 10.2.2.1
    vlan.31:
      id: 31
      link: bond1
      addresses:
      - 10.3.0.1/24
      nameservers:
        addresses:
        - 10.3.0.1
    vlan.32:
      id: 32
      link: bond1
      addresses:
      - 10.3.1.1/24
      nameservers:
        addresses:
        - 10.3.1.1
    vlan.33:
      id: 33
      link: bond1
      addresses:
      - 10.3.2.1/24
      nameservers:
        addresses:
        - 10.3.2.1
  version: 2